name: harvest
description: Harvest Project App Client
publish_to: none
version: 2026.0128.01+215
environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.6.0
  get: ^4.7.2
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  qbittorrent_api: ^1.3.1
  transmission_api: ^0.0.2
  easy_refresh: ^3.4.0
  url_launcher: ^6.3.2
  tmdb_api: ^2.2.3
  dio_smart_retry: ^7.0.1
  path: ^1.9.0
  basic_utils: ^5.7.0
  flutter_ellipsis_text: ^1.0.1
  syncfusion_flutter_core: ^31.1.17
  syncfusion_flutter_charts: ^31.1.17
  flutter_slidable: ^4.0.0
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.0.0
  random_color: ^1.0.5
  package_info_plus: ^9.0.0
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.0
  flutter_popup: ^3.3.0
  xpath_selector_html_parser: ^3.0.1
  html: ^0.15.4
  collection: ^1.19.0
  custom_rating_bar: ^3.0.0
  window_manager: ^0.5.1
  dartssh2_plus: ^3.0.0
  flutter_floating: ^2.0.1
  timelines_plus: null
  file_picker: ^10.3.8
  flutter_markdown_plus: ^1.0.3
  share_plus: ^12.0.1
  image_gallery_saver_plus: ^4.0.1
  pasteboard: ^0.4.0
  web_socket_channel: ^3.0.3
  multi_select_flutter: ^4.1.3
  image_picker: ^1.2.0
  android_intent_plus: ^6.0.0
  photo_view: ^0.15.0
  shadcn_ui: ^0.28.0
  media_kit: ^1.2.0
  media_kit_video: ^2.0.1
  media_kit_libs_android_video: ^1.3.7
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.2.1
  install_plugin_v3: ^3.1.3
  device_info_plus: ^11.0.0
  flutter_colorpicker: ^1.1.0
  mime: ^2.0.0
  flutter_cache_manager: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
